### ISSUE TITLE
Make the views dynamic

### ISSUE THREAD

**Issue by rajdeepbharati** [macports/buildbot-macports-custom-views#22]
New builds/changes should automatically pop up, like in the default buildbot views.

**Comment by rajdeepbharati** [comment]
@tardyp Should I try doing this without the data module (using something like https://github.com/probil/vue-socket.io-extended)

**Comment by tardyp** [comment]
The data-module should not be coupled to angularjs or vue.js. At the moment it uses some angular.js API, but this is quite limited.

Current problem with vue, is that the Collection class is a subclass or Array, and implement more method on top of the Array API (like put or get)
Collection is the object type that is returned by all the getXX() api or data module.
Vue will detect the that Collection is an array, and add its own properties to it, in an incompatible way. 
What I originally did in the boilerplate template is to make a copy of the collection in a normal array, inside the onUpdate callback, and transmit that to vue component, instead of the collection.

What we should do is to understand the incompatibility problem and fix it properly in data-module, so that we don't have to copy the data.

I would recommend you dive into the data-module to understand how it is structured. Please look at the collection class and how it is subclassed by other types. No need to go too far into restService or WSService.
This is done using angularJS services, but this does not need to be like this.

One good improvement would be to first translate it (the collection class hierachy) into typescript, so that it is easier to reason and to work with. 

You can also try to fix the vue incompatibility with a simple fix, if you don't want to invest to much into data-module.

**Comment by rajdeepbharati** [comment]
Ok, thanks a lot for the insight

**Comment by rajdeepbharati** [comment]
@tardyp after applying https://github.com/buildbot/buildbot/pull/4973, live updates are working when I do something simple like:
```vue
<div v-for="build in builds" :key="build.buildid">{{build.builderid}}/{{build.number}}<br></div>
```

However, with the tables (complex ui it isn't working yet). Maybe I have to handle the methods/computed functions in a different manner. I'll keep digging 👍

**Comment by rajdeepbharati** [comment]
Closed via https://github.com/macports/buildbot-macports-custom-views/pull/21
